# Generated by Django 4.2.3 on 2023-08-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.CharField(max_length=100, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.CharField(max_length=100, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображеие')),
                ('category', models.CharField(max_length=100, verbose_name='категории')),
                ('purchase_price', models.CharField(verbose_name='цена за пкупку')),
                ('creation_date', models.TimeField(verbose_name='дата создания')),
                ('last_modified_date', models.TimeField(verbose_name='дата последнего изменения')),
            ],
        ),
    ]
