# Generated by Django 4.2.3 on 2023-08-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(verbose_name='цена за пкупку'),
        ),
    ]
